# Development-only compose file. Not a production example.
services:
  server:
    container_name: Lingarr.Server
    build:
      context: .
      dockerfile: Lingarr.Server/Dockerfile
      args:
        BUILD_CONFIGURATION: Debug
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - ASPNETCORE_URLS=http://+:9876
      - DB_CONNECTION=sqlite
    volumes:
      - config:/app/config
    ports:
      - "9877:9876"

  client:
    container_name: Lingarr.Client
    image: node:alpine
    working_dir: /app
    ports:
      - "9876:9876"
    volumes:
      - ./Lingarr.Client:/app:rw
      - node_modules:/app/node_modules
    command: /bin/sh -c "npm install && npm run dev"

volumes:
  config:
  node_modules:
